databases:
- name: temporal-db
  databaseName: temporal
  postgresMajorVersion: "13"
  user: temporal
  plan: free
  region: oregon

services:
- name: temporal
  type: pserv
  autoDeploy: false
  plan: starter
  region: oregon
  runtime: docker
  image:
    url: docker.io/temporalio/auto-setup:1.25.1
  envVars:
  - key: PORT
    value: 7233
  - key: DYNAMIC_CONFIG_FILE_PATH
    value: /etc/temporal/dynamicconfig.yaml
  - key: DB
    value: postgres12
  - key: DBNAME
    fromDatabase:
      name: temporal-db
      property: database
  - key: DB_PORT
    fromDatabase:
      name: temporal-db
      property: port
  - key: POSTGRES_USER
    fromDatabase:
      name: temporal-db
      property: user
  - key: POSTGRES_PWD
    fromDatabase:
      name: temporal-db
      property: password
  - key: POSTGRES_SEEDS
    fromDatabase:
      name: temporal-db
      property: host
- name: temporal-admin-tools
  type: pserv
  autoDeploy: false
  plan: starter
  region: oregon
  runtime: docker
  image:
    url: docker.io/temporalio/admin-tools:1.25.1-tctl-1.18.1-cli-1.1.0
- name: temporal-ui
  type: pserv
  autoDeploy: false
  plan: starter
  region: oregon
  runtime: docker
  image:
    url: docker.io/temporalio/ui:2.26.2
  envVars:
  - key: PORT
    value: 8088
- type: web
  repo: https://github.com/render-examples/sample-temporal-app
  name: app-workflow-trigger
  plan: starter
  region: oregon
  runtime: go
  buildCommand: go build start/main.go
  startCommand: ./main
  envVars:
  - key: TEMPORAL_CLUSTER_HOST
    fromService:
      name: temporal
      type: pserv
      property: host
- type: worker
  repo: https://github.com/render-examples/sample-temporal-app
  name: app-worker
  plan: starter
  region: oregon
  runtime: go
  buildCommand: go build worker/main.go
  startCommand: ./main
  envVars:
  - key: TEMPORAL_CLUSTER_HOST
    fromService:
      name: temporal
      type: pserv
      property: host